# Generated by Django 5.0.1 on 2024-01-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10, verbose_name='Transmission')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deposit')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('cost_of_rental', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost of Rental')),
                ('available_start_date', models.DateField(verbose_name='Available Start Date')),
                ('available_end_date', models.DateField(verbose_name='Available End Date')),
            ],
        ),
    ]
