# Generated by Django 5.0.1 on 2024-01-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentApp', '0003_userinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
