# Generated by Django 5.0.1 on 2024-01-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentApp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Photo URL'),
        ),
    ]
