# Generated by Django 5.0.1 on 2024-01-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentApp', '0006_car_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo_url',
        ),
    ]
