# Generated by Django 5.0.1 on 2024-01-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentApp', '0007_remove_car_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/', verbose_name='Car Photo'),
        ),
    ]
