# Generated by Django 5.0.1 on 2024-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentApp', '0008_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Model'),
        ),
    ]
